/**
 * Natural-language explanation (HU10), in neutral Spanish. Generated by deterministic rules over
 * the computed indicators, without external services. Descriptive only: it states what happens
 * and what causes it, never what the user should do (rule 4).
 */
export interface Explanation {
  /** Sentence naming the factor that determines the result. */
  readonly summary: string;
  /** One sentence per applied decision or relevant factor, in application order. */
  readonly details: readonly string[];
}
